GET localhost:8000/v1/files/download/72cafa54-1515-43c8-8df9-d4be1f39d378
Cookie: token=T+ub+mkUZRlfpac6UhWkrZX1KtgqE40xu2J5Nc0BQkpRx9s3AEoYs6sqnNDSlOgfH%2FJOG%2Farp3G0JtpdnrWCdGRpXWE93BNvCzETb+3hEgF7eZDEGbI8C0aWbgZKLvMeg4xDYd+jDzEsddyknuQBRmHzmonkNI5yzDz47oBlD2DLRXmm4U2%2F7HW36OPX7mYuz0NxNzwUL%2F1g5f81FMdYVaO8AyA1mVJMYrvZ3NSFTpsse84Z+fezBcuruzCYyQyTk9Ea8Veg3APcu%2FrbUmprSLX%2FnEoIkIMCq59%2FsW+SQw8776eTpp9PqSbBuPV5lxMi4BXxtmMmx+4VqJcS8jbAp7DOXCg9%2Fbf6xk041gFa%2F8AibQsB4FC0EKc%3D; HttpOnly; SameSite=Strict
